//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCare.EntityFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointmenttable
    {
        public int AppId { get; set; }
        public string patient { get; set; }
        public string Treatment { get; set; }
        public System.DateTime AppDate { get; set; }
    }
}
