//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCare.EntityFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentalCareEntities : DbContext
    {
        public DentalCareEntities()
            : base("name=DentalCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointmenttable> Appointmenttables { get; set; }
        public virtual DbSet<Patienttable> Patienttables { get; set; }
        public virtual DbSet<Prescriptiontable> Prescriptiontables { get; set; }
        public virtual DbSet<Treatmenttable> Treatmenttables { get; set; }
        public virtual DbSet<Usertable> Usertables { get; set; }
    }
}
