//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCare.EntityFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patienttable
    {
        public int PatId { get; set; }
        public string PatName { get; set; }
        public string PatPhone { get; set; }
        public string PatAddress { get; set; }
        public System.DateTime PatDOB { get; set; }
        public string PatGender { get; set; }
        public string PatAllergies { get; set; }
    }
}
