//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCare.EntityFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescriptiontable
    {
        public int PrescId { get; set; }
        public string PatName { get; set; }
        public string TreatmentName { get; set; }
        public string TreatmentCost { get; set; }
        public string Medicines { get; set; }
        public int MedQty { get; set; }
    }
}
