//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCare.EntityFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usertable
    {
        public int UId { get; set; }
        public string UName { get; set; }
        public string UPass { get; set; }
        public string Phone { get; set; }
    }
}
