//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EmpId { get; set; }
        public string EmapName { get; set; }
        public Nullable<int> EmpSalary { get; set; }
        public Nullable<int> DeptID { get; set; }
    
        public virtual DEPT DEPT { get; set; }
    }
}
