--CREATE TABLE DEPT(DeptID INT, DeptName VARCHAR(100));

/*INSERT INTO DEPT VALUES(1,'MICROSOFT');
INSERT INTO DEPT VALUES(2,'SAP');
INSERT INTO DEPT VALUES(3,'SALESFORCE');
INSERT INTO DEPT VALUES(4,'IT');*/

INSERT INTO DEPT VALUES(5,'ML');
SELECT * FROM DEPT;