SELECT AVG(EMPSALARY)
FROM EMPLOYEE
WHERE EMPSALARY > 70000;


SELECT COUNT(Distinct(EMPDEPTID)) AS "Total" FROM Employee

SELECT COUNT(Distinct(EMPDEPTID)) AS "Total" FROM Employee


SELECT EMPDEPTID, COUNT(*) AS "Total Employees" 
FROM Employee
GROUP BY EMPDEPTID;

SELECT MAX(EMPSALARY) AS "Highest Salary" FROM Employee;

SELECT EMPDEPTID, MAX(EMPSALARY) AS "Highest Salary" 
FROM Employee
GROUP BY EMPDEPTID;

SELECT MIN(EMPSALARY) AS "Smallest Salary" FROM Employee;

SELECT EMPDEPTID, MIN(EMPSALARY) AS "Smallest Salary" 
FROM Employee
GROUP BY EMPDEPTID;

SELECT EMPDEPTID, SUM(EMPSALARY) as SALARY_SUM
FROM EMPLOYEE 
GROUP BY EMPDEPTID;

SELECT SUM(EMPSALARY) AS "Total Salary" FROM Employee;

